Add files via upload

diff --git a/iso2usb b/iso2usb
--- a/iso2usb
+++ b/iso2usb
@@ -1,7 +1,8 @@
-#!/bin/bash
+#!/usr/bin/env bash
+# Write an .iso or .img file to a USB using dd
+# May need to unmount partitions of device prior if there are any(e.g.): 'sudo umount /dev/sda*'
 
-# Write an ISO to USB
-
+# Takes a string as an argument to provide colored output
 info()
 {
     echo -e "\n\033[1;32m==> $*\033[0m"
@@ -10,11 +11,11 @@ info()
 read -rp "Enter directory containing ISO image: " iso_dir
 
 if [[ ! -d "$iso_dir" ]];then
-	echo "Directory not found"
+	echo "$iso_dir not found"
 	exit 1
 fi
 
-mapfile -t iso < <(find "$iso_dir" -maxdepth 1 -type f -name "*.iso")
+mapfile -t iso < <(find "$iso_dir" -maxdepth 1 -type f \( -name "*.iso" -o -name "*.img" \))
 
 if [[ ${#iso[@]} -eq 0 ]];then
 	echo "No iso files in $iso_dir"
@@ -23,30 +24,36 @@ fi
 
 info "Available iso's in $iso_dir:"
 for i in "${!iso[@]}";do
-	echo "[$i] ${iso[$i]}"
+	echo "[$i] ${iso[$i]##*/}"
 done
 
-read -rp "Enter the number of the ISO to write to USB: " iso_num
-
+read -rp "Enter number for ISO to write to USB: " iso_num
 img=${iso[$iso_num]}
+[[ -z $img ]] && { echo "Incorrect input: $iso_num"; exit 1; }
 
-info "Available devices: "
-lsblk -lp
-echo
+mapfile -t block < <(lsblk -no PATH)
 
-read -rp "Enter device path (e.g. /dev/sdb): " device
+info "Available devices:"
+for j in "${!block[@]}";do
+	echo "[$j] ${block[$j]}"
+done
+
+read -rp "Enter number for device to write to: " blk_num
+device=${block[$blk_num]}
+[[ -z $device ]] && { echo "Incorrect input: $blk_num"; exit 1; }
 
 info "Your final selections:"
-echo "ISO:	  $img"
+echo "ISO:	 $img"
 echo "Device:  $device"
-read -rp "This will erase all data on $device! Continue? (y/N): " confirm
+
+read -rp "This will erase all data on ${device}! Continue? (y/N): " confirm
 
 if [[ "$confirm" != [yY] ]];then 
 	echo "Aborted"
 	exit 1
 fi
 
-info "Writing to $device..."
+info "Writing to ${device}..."
 sudo dd if="$img" of="$device" bs=4M status=progress conv=fsync
 
 info "Ejecting $device..."
